### ISSUE TITLE
Bug found in Hoplite keyboard app ( keyboard text is not showing on keyboard button

### ISSUE THREAD

**Issue by nasirshah1813** [jeremymarch/HopliteKB-Android#3]
#### Project Information

* Repository: https://github.com/jeremymarch/HoplitePolytonicKeyboardAndroid

* Project Name:  HoplitePolytonicKeyboardAndroid 

* Publisher   : jeremymarch
 
#### Expected behavior
According to my knowledge when i open the hop lite keyboard after click on the 123 tab should be show the text on button of keyboard 

#### Actual behavior
After open the application when i open the 123 tab  and i see the there are no show any text in button of key board 

#### How to reproduce
* download app from f droid 
* and install and open the application
* click on test button
* click on 123 tab 
* note the bug 
* Browser:   Hoplite keyboard  1.2.2
* Operating system: android version 6.0.1
 

#### Recording Of The Bug
https://youtu.be/U0-6PitelM0
#### Proof of Work Done   
https://github.com/nasirshah1813

**Comment by jeremymarch** [comment]
Thanks for reporting this.  The unicode characters for those keys which show up blank are not provided by most fonts.  For this reason I include the font New Athena Unicode in the app and it should be using that font for these characters.  I'll investigate why this is not happening.  This seems to be an F-Droid-only bug, so there could be an issue with how F-Droid handles fonts bundled with an app.
